services:
  _defaults:
    autowire: true
    autoconfigure: true

  ICS\CelebrityBundle\Controller\:
    resource: "../../Controller"
    tags: ['controller.service_arguments']
  ICS\CelebrityBundle\Service\:
    resource: "../../Service"
    tags: ['controller.service_arguments']
  ICS\CelebrityBundle\DataFixtures\:
    resource: "../../DataFixtures"
    tags: ['doctrine.fixture.orm']